# Generated by Django 3.2.13 on 2022-09-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinationcoordinate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='destinationcoordinate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='origincoordinate',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22),
        ),
        migrations.AlterField(
            model_name='origincoordinate',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=22),
        ),
    ]
