# Generated by Django 3.2.13 on 2022-09-07 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="destination",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destination",
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="origin",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="origin",
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="route",
            name="truck_driver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.truckdriver"
            ),
        ),
    ]
